apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.fullname" . }}
stringData:
  ACCEPT_EULA: {{ .Values.msssql.acceptEula }}
  MSSQL_SA_PASSWORD: {{ .Values.msssql.saPassword }}
  MSSQL_PID: {{ required ".Values.mssql.pid required" .Values.mssql.pid }}
  TZ: {{ .Values.msssql.timezone }}