apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.fullname" . }}
stringData:
  ACCEPT_EULA: '{{ .Values.mssql.acceptEula }}'
  MSSQL_SA_PASSWORD: {{ .Values.mssql.saPassword }}
  MSSQL_PID: {{ required ".Values.mssql.pid required" .Values.mssql.pid }}
  TZ: {{ .Values.mssql.timezone }}