apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.fullname" . }}_lb
  labels:
    {{- include "mssql.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mssql
      protocol: TCP
      name: mssql
  selector:
    {{- include "mssql.selectorLabels" . | nindent 4 }}
