apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sqlpad.fullname" . }}
stringData:
  SQLPAD_ADMIN: {{ .Values.sqlpad.admin | quote }}
  SQLPAD_ADMIN_PASSWORD: {{ .Values.sqlpad.password | squote }}
  SQLPAD_APP_LOG_LEVEL: {{ required ".Values.sqlpad.logLevel required" .Values.sqlpad.logLevel  | quote }}
  SQLPAD_PORT: "3000"
  {{- range .Values.sqlpad.connections }}
  SQLPAD_CONNECTIONS__{{ .uid }}__name: {{ .name | quote }}
  SQLPAD_CONNECTIONS__{{ .uid }}__driver: {{ .driver | quote }}
  SQLPAD_CONNECTIONS__{{ .uid }}__host: {{ .host | quote }}
  SQLPAD_CONNECTIONS__{{ .uid }}__database: {{ .database | quote }}
  SQLPAD_CONNECTIONS__{{ .uid }}__username: {{ .username | quote }}
  SQLPAD_CONNECTIONS__{{ .uid }}__password: {{ .password | squote }}
  {{- end }}
  