apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sqlpad.fullname" . }}
  labels:
    {{- include "sqlpad.labels" . | nindent 4 }}
spec:
  serviceName: "mssqlpad"
  selector:
    matchLabels:
      {{- include "sqlpad.selectorLabels" . | nindent 6 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sqlpad.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sqlpad.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 35217
          envFrom:
          - secretRef:
              name: {{ include "sqlpad.fullname" . }}
      volumeMounts:
        - mountPath: /var/lib/sqlpad/
          name: {{ include "sqlpad.fullname" . }}-data
      # serviceAccount: sa-with-anyuid
    volumeClaimTemplates:
    - metadata:
        name: {{ include "sqlpad.fullname" . }}-data
        labels:
        {{- include "sqlpad.labels" . | nindent 12 }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.sqlpad.storageSize }}