apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  serviceName: "mssql"
  selector:
    matchLabels:
      app: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/rhel/server:2019-CU15-rhel-8.4 
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "0.5"
              memory: "4Gi"
          lifecycle:
          env:
            - name: ACCEPT_EULA
              value: 'Y'
            - name: MSSQL_SA_PASSWORD
              value: 'M$$sqlPassword'
            - name: MSSQL_PID
              value: 'Express'
            - name: TZ
              value: 'Asia/Singapore'
          ports:
            - containerPort: 1443
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: mssqldata
  volumeClaimTemplates:
  - metadata:
      name: mssqldata
    labels:
      app: mssql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi